### ISSUE TITLE
Speicherleck

### ISSUE THREAD

**Issue by edyso** [ioBroker/ioBroker.modbus#514] opened 2024-05-30 13:28 UTC
**Describe the bug**  
Speicherverbrauch der Modbus-Instanz wächst pro Tag um ca. 70-80MB

**To Reproduce**  
nach jedem Restart startet der Speicherverbrauch bei 75MB und wächst täglich.

**Screenshots & Logfiles** 
Über die Debug-Console scheint ein Timer-Array (_timers) für den Speicherverbrauch verantwörtlich zu sein.
![1](https://github.com/ioBroker/ioBroker.modbus/assets/86227862/15a6919a-116c-4892-b87a-98c5ce59cbc6)
![3](https://github.com/ioBroker/ioBroker.modbus/assets/86227862/ce013cd7-fd40-49d0-9551-55fd57e6375c)

**Versions:**  
 - Adapter version: 6.1.0 auch 6.2.3
 - JS-Controller version: 5.0.19
 - Node version: 18.20.2
 - Operating system: Debian

**Comment by Apollon77** [comment] 2024-05-31 15:31
Good catch ...

**Comment by Apollon77** [comment] 2024-05-31 15:32
@edyso Can oyu please try GitHub version and verify that the issue is fixed with this?

**Closed** 2024-05-31 15:32 UTC
Labels: bug

**Comment by edyso** [comment] 2024-05-31 20:19
I'm testing...I'll report tomorrow.
For your information, my pooling-time is 100ms, I've a push button

**Comment by Apollon77** [comment] 2024-05-31 22:22
Thank you, looking forward to your results

**Comment by edyso** [comment] 2024-06-01 05:02
I'm sorry, but the _timers array is stil growing, after round about 8 hours the length of array is 975573 (number after @).
Your fix affects the lib/master.js so I checked if the file on my server is the same like on github.

**Comment by Apollon77** [comment] 2024-06-01 13:22
And you made sure that the instance had restarted after installing the update from GitHub? Because the version did not change it could be that there was no auto restart? or did you restaretd manually?

**Comment by edyso** [comment] 2024-06-01 16:34
I'm sure that the changes made by you are live, first I was confused about the version, than I checked the file that the modifications are included and I inserted a log row. After restart I get the log entry.

**Comment by edyso** [comment] 2024-10-17 09:41
The bug is still present in the current verion 6.3.2.
My workaround is to restart the adapter every 24h or to set a memory limit, this ends with log entries, maybe there are also sentry entries...
